### ISSUE TITLE
 Unhandled Exception: NoSuchMethodError: The method 'toJsonMap' was called on nul

### ISSUE THREAD

**Issue by 0123cf** [jpush/jverify-flutter-plugin#27]
详细报错信息
```
I/flutter ( 4066): 一键登录 token code: 2000 运营商: CT _token: null
E/flutter ( 4066): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'toJsonMap' was called on null.
E/flutter ( 4066): Receiver: null
E/flutter ( 4066): Tried calling: toJsonMap()
E/flutter ( 4066): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
E/flutter ( 4066): #1      Jverify.setCustomAuthorizationView (package:jverify/jverify.dart:229:32)
E/flutter ( 4066): #2      _ScaffoldRouteState.loginAuth (package:cjyy/main.dart:67:13)
```

**Comment by 0123cf** [comment]
是参数传入问题
