### ISSUE TITLE
运行example报错

### ISSUE THREAD

**Issue by seek-x2y** [jpush/jverify-flutter-plugin#37]
我在本地运行example，报错：
>  Could not update files on device: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:64232/OrbjUzIuj6Q=/

我先是采用模拟器调试，也是报错这个，之后又换了真机，仍旧报这个错，手机上安装了example的apk，控制台输出信息具体如下：
```
Launching lib\main.dart on STF AL10 in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\apk\debug\app-debug.apk.
Syncing files to device STF AL10...
I/flutter ( 3105): | JVER | Flutter | setDebugMode
D/| JVER | Android | -( 3105): onMethodCall:setDebugMode
D/| JVER | Android | -( 3105): Action - setDebugMode:
I/flutter ( 3105): | JVER | Flutter | setup
E/JIGUANG-JCore( 3105): [JDB] context is null
D/ActionManager( 3105): addAction type:JVERIFICATION,action:cn.jiguang.av.g
D/| JVER | Android | -( 3105): onMethodCall:setup
D/| JVER | Android | -( 3105): Action - setup:
D/JIGUANG-VERIFICATION( 3105): [JVerificationInterface] JVerificationInterface localInit...version:2.5.2 ,buildId:304
I/JIGUANG-JCore( 3105): [JCoreGobal] action:init jcore,version:2.1.6,build id:53
D/JIGUANG-JCore( 3105): [CheckManifestHelper] manifest:channel - developer-default
W/KeyStore( 3105): KeyStore exception
W/KeyStore( 3105): android.os.ServiceSpecificException:  (code 7)
W/KeyStore( 3105): 	at android.os.Parcel.createException(Parcel.java:1967)
W/KeyStore( 3105): 	at android.os.Parcel.readException(Parcel.java:1921)
W/KeyStore( 3105): 	at android.os.Parcel.readException(Parcel.java:1871)
W/KeyStore( 3105): 	at android.security.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:786)
W/KeyStore( 3105): 	at android.security.KeyStore.get(KeyStore.java:195)
W/KeyStore( 3105): 	at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificate(AndroidKeyStoreSpi.java:144)
W/KeyStore( 3105): 	at java.security.KeyStore.getCertificate(KeyStore.java:1120)
W/KeyStore( 3105): 	at com.cmic.sso.sdk.utils.f.a(KeystoreUtil.java:45)
W/KeyStore( 3105): 	at com.cmic.sso.sdk.auth.AuthnHelper$1.a(AuthnHelper.java:107)
W/KeyStore( 3105): 	at com.cmic.sso.sdk.utils.w$a.run(ThreadUtils.java:62)
W/KeyStore( 3105): 	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
W/KeyStore( 3105): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
W/KeyStore( 3105): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/KeyStore( 3105): 	at java.lang.Thread.run(Thread.java:784)
W/KeyStore( 3105): KeyStore exception
W/KeyStore( 3105): android.os.ServiceSpecificException:  (code 7)
W/KeyStore( 3105): 	at android.os.Parcel.createException(Parcel.java:1967)
W/KeyStore( 3105): 	at android.os.Parcel.readException(Parcel.java:1921)
W/KeyStore( 3105): 	at android.os.Parcel.readException(Parcel.java:1871)
W/KeyStore( 3105): 	at android.security.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:786)
W/KeyStore( 3105): 	at android.security.KeyStore.get(KeyStore.java:195)
W/KeyStore( 3105): 	at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificate(AndroidKeyStoreSpi.java:149)
W/KeyStore( 3105): 	at java.security.KeyStore.getCertificate(KeyStore.java:1120)
W/KeyStore( 3105): 	at com.cmic.sso.sdk.utils.f.a(KeystoreUtil.java:45)
W/KeyStore( 3105): 	at com.cmic.sso.sdk.auth.AuthnHelper$1.a(AuthnHelper.java:107)
W/KeyStore( 3105): 	at com.cmic.sso.sdk.utils.w$a.run(ThreadUtils.java:62)
W/KeyStore( 3105): 	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
W/KeyStore( 3105): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
W/KeyStore( 3105): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/KeyStore( 3105): 	at java.lang.Thread.run(Thread.java:784)
D/JIGUANG-VERIFICATION( 3105): [JVerificationInterface] localInit sdk result: cm=true cu=true ct=true
D/JIGUANG-VERIFICATION( 3105): [JVerificationInterface] localInit sdk done
D/JIGUANG-JCommon( 3105): [JCommonInterface] onEvent action:service_create
D/JIGUANG-VERIFICATION( 3105): [VerifyConfig] config expired . refresh config
D/JIGUANG-VERIFICATION( 3105): [VerifyConfig] [fetch] fetch remote config start .
D/JIGUANG-JCommon( 3105): [JCommonInterface] onEvent action:get_receiver
D/AwareBitmapCacher( 3105): handleInit switch not opened pid=3105
D/NetworkSecurityConfig( 3105): No Network Security Config specified, using platform default
D/JIGUANG-JCommon( 3105): [JCommonInterface] onEvent action:set_sdktype_info
D/JIGUANG-JCore( 3105): [JCoreTCPManager] Action - restartNetworkingClient, pid:3105
I/JIGUANG-JCore( 3105): [NetworkingClient] Begin to run in ConnectingThread - id:70224
D/JIGUANG-JCommon( 3105): [JCommonInterface] onEvent action:get_imei
W/pool-14-thread-( 3105): type=1400 audit(0.0:1460111): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=14522 scontext=u:r:untrusted_app:s0:c183,c257,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
E/libc    ( 3105): Access denied finding property "vendor.cellular.ril.imsi"
E/ActivityThread( 3105): Failed to find provider info for com.yangcong345.android.phone.DownloadProvider
E/ActivityThread( 3105): Failed to find provider info for com.kekeclient_.DownloadProvider
E/ActivityThread( 3105): Failed to find provider info for com.gps.vili.DownloadProvider
E/ActivityThread( 3105): Failed to find provider info for com.smart_invest.marathonappforandroid.DownloadProvider
D/JIGUANG-JCommon( 3105): [JCommonInterface] onEvent action:get_loc_info
D/JIGUANG-JCore( 3105): [ConnectingHelper] udp Receiving...
W/JIGUANG-VERIFICATION( 3105): [VerifyConfig] fetch failed, msg=not validate user
D/JIGUANG-VERIFICATION( 3105): [VerifyConfig] [fetch] fetch remote config failed. lasts = 490
E/AndroidRuntime( 3105): FATAL EXCEPTION: pool-4-thread-1
E/AndroidRuntime( 3105): Process: cn.jiguang.xx, PID: 3105
E/AndroidRuntime( 3105): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-4-thread-1
E/AndroidRuntime( 3105): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:793)
E/AndroidRuntime( 3105): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:683)
E/AndroidRuntime( 3105): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:77)
E/AndroidRuntime( 3105): 	at io.flutter.embedding.engine.dart.DartExecutor$DefaultBinaryMessenger.send(DartExecutor.java:379)
E/AndroidRuntime( 3105): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:137)
E/AndroidRuntime( 3105): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
E/AndroidRuntime( 3105): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
E/AndroidRuntime( 3105): 	at com.jiguang.jverify.JverifyPlugin$1.onResult(JverifyPlugin.java:130)
E/AndroidRuntime( 3105): 	at com.jiguang.jverify.JverifyPlugin$1.onResult(JverifyPlugin.java:123)
E/AndroidRuntime( 3105): 	at cn.jiguang.verifysdk.api.VerifySDK$3$1.a(Unknown Source:89)
E/AndroidRuntime( 3105): 	at cn.jiguang.verifysdk.api.VerifySDK$3$1.onResult(Unknown Source:2)
E/AndroidRuntime( 3105): 	at cn.jiguang.verifysdk.api.VerifySDK$5.run(Unknown Source:85)
E/AndroidRuntime( 3105): 	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
E/AndroidRuntime( 3105): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
E/AndroidRuntime( 3105): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 3105): 	at java.lang.Thread.run(Thread.java:784)
D/JIGUANG-JCommon( 3105): [JCommonInterface] onEvent action:deviceinfo
D/JIGUANG-JCore( 3105): [ConnTask] Open connection with ip=/121.46.30.60, port:7007
W/System  ( 3105): A resource failed to call close. 
W/cn.jiguang.xx( 3105): Accessing hidden method Landroid/telephony/TelephonyManager;->getSimCount()I (light greylist, reflection)
W/cn.jiguang.xx( 3105): Accessing hidden method Landroid/telephony/TelephonyManager;->getSimSerialNumber(I)Ljava/lang/String; (light greylist, reflection)
W/cn.jiguang.xx( 3105): Accessing hidden method Landroid/telephony/TelephonyManager;->getSubscriberId(I)Ljava/lang/String; (light greylist, reflection)
W/cn.jiguang.xx( 3105): Accessing hidden method Landroid/telephony/SubscriptionManager;->getSubId(I)[I (light greylist, reflection)
E/libc    ( 3105): Access denied finding property "vendor.cellular.ril.imsi"
E/JIGUANG-JCore( 3105): [ReportUtils] wrap data failed
I/Process ( 3105): Sending signal. PID: 3105 SIG: 9
Lost connection to device.
Could not update files on device: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:49159/mM083HMGAVE=/
```
网上查了，又说这个是'.'错误，有说让用真机的，我都看了，不解决问题，请问这个怎么回事？

**Comment by cool-518** [comment]
我也是这个问题，KeyStore exception
