### ISSUE TITLE
fetch loginToken failed:[CT,（80801)WIFI切换异常]

### ISSUE THREAD

**Issue by mlch12333** [jpush/jverify-flutter-plugin#73]
安卓手机，在WiFi和移动网络同时打开的情况下，获取loginToken失败。fetch loginToken failed:[CT,（80801)WIFI切换异常]。

**Comment by skill20** [comment]
发一下整个日志

**Comment by janiokq** [comment]
2020-10-22 09:56:26.488 2345-2345/? I/Icon_Cache: removeByPackageName: key = 2131492965#com.zhucheng.blue_app
2020-10-22 09:56:26.489 2345-2345/? I/HwLauncher: PowerSaveLauncherModel onPackageChanged packageName = com.zhucheng.blue_app user = UserHandle{0}
2020-10-22 09:56:26.489 2345-2345/? E/HwLauncher: PowerSaveLauncherModel onPackageChanged: not inPowerSaveLauncher 
2020-10-22 09:56:26.490 2345-2345/? I/HwLauncher: StreetModeLauncherModel onPackageChanged packageName = com.zhucheng.blue_app,user = UserHandle{0}
2020-10-22 09:56:26.490 2345-2345/? E/HwLauncher: StreetModeLauncherModel onPackageChanged: not inStreetModeLauncher 
2020-10-22 09:56:26.465 1352-1695/? I/chatty: uid=1000(system) android.bg identical 1 line
2020-10-22 09:56:26.465 1352-1695/? I/HwResolverManager: isMultiScreenCollaborationEnabled: Operate settings exception! 
2020-10-22 09:56:26.490 1352-10934/? I/HwResolverManager: isMultiScreenCollaborationEnabled: Operate settings exception! 
2020-10-22 09:56:26.797 744-744/? E/WifiHAL: enter wifi_get_link_stats
2020-10-22 09:56:26.799 1352-1829/? I/WificondControl: Noise: 0, Snr: -1, Chload: 112, rssi: -53, txBitrate: 390, rxBitrate: 292, frequency: 5745, UlDelay: -1, currentTxBytes: 7857755, currentTxPackets: 83031, currentTxFailed: 7, currentRxBytes: 141770228, currentRxPackets: 123020
2020-10-22 09:56:26.803 1352-1829/? V/HwWifiServiceFactory: get AllImpl object = com.android.server.wifi.HwWifiServiceFactoryImpl@1631d0d
2020-10-22 09:56:26.490 1352-10934/? I/chatty: uid=1000(system) Binder:1352_1A identical 1 line
2020-10-22 09:56:26.491 1352-10934/? I/HwResolverManager: isMultiScreenCollaborationEnabled: Operate settings exception! 
2020-10-22 09:56:26.804 1352-1695/? I/RoleUserState: Wrote roles.xml successfully
2020-10-22 09:56:26.809 1352-1829/? I/TelephonyManager: getAllCellInfo calling app is android
2020-10-22 09:56:26.809 2308-3255/? W/PhoneInterfaceManager: shouldBlockLocation running ...
2020-10-22 09:56:26.810 2308-3255/? I/PhoneInterfaceManager: shouldBlockLocation  ret:false
2020-10-22 09:56:26.819 914-11302/? I/Pged-IPgedBinderService: ****action is 2, pid num is 5***
2020-10-22 09:56:26.820 914-11302/? I/Pged-Freezer: thawPids
2020-10-22 09:56:26.823 2283-2660/? D/PgedBinderAdapter: unF_Z ok, pid: [4446, 1614, 8565, 4195]
2020-10-22 09:56:27.015 1352-1839/? I/ConnectivityService: releasing NetworkRequest [ REQUEST id=105, [ Transports: CELLULAR Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN Uid: 10201 DNN:  SSCMODE: 0 SNSSAI:  PduSessionType: 0 RouteBitmap: 0] ] (release request)
2020-10-22 09:56:27.019 20336-20336/? D/| JVER | Android | -: code=6001, message=fetch loginToken failed:[CT,（80800)WIFI切换超时]
2020-10-22 09:56:27.027 2308-2308/? V/TpProviderHw: insert begin subId = 1, match is 2
2020-10-22 09:56:27.027 20336-20374/? I/flutter: handleMethod method = onReceiveLoginAuthCallBackEvent
2020-10-22 09:56:27.027 1352-22662/? D/HwConnectivityServiceEx: set 10201 wlan0 value false
2020-10-22 09:56:27.028 20336-20374/? I/flutter: 通过添加监听，获取到 loginAuthSyncApi 接口返回数据，code=6001,message = fetch loginToken failed:[CT,（80800)WIFI切换超时],operator = null
2020-10-22 09:56:27.034 2308-2308/? D/Telephony-AccountEntry: isEmergencyPreferredAccount: subId=1, activeData=1
2020-10-22 09:56:27.034 2308-2308/? D/Telephony-AccountEntry: isEmergencyPreferredAccount: Device does not require preference.
2020-10-22 09:56:27.034 2308-2308/? D/Telephony-AccountEntry: isEmergencyPreferredAccount: subId=1, activeData=1
2020-10-22 09:56:27.034 2308-2308/? D/Telephony-AccountEntry: isEmergencyPreferredAccount: Device does not require preference.
2020-10-22 09:56:27.378 2249-2563/? I/ConnCureStateMonitor: handleMessage: msg[4]
2020-10-22 09:56:27.382 2249-2563/? I/ConnCureStateMonitor: canPerformConnCure: wifi link normally
2020-10-22 09:56:27.544 20655-20655/? I/HiTraceC: entered LogRegisterGetIdFun
2020-10-22 09:56:27.544 20655-20655/? I/HiTraceC: entered HiTraceInit
2020-10-22 09:56:27.757 1352-1828/? I/TrafficMonitor: update:rxPkts:4,txPkts:3,rxBytes:236,txBytes:220
2020-10-22 09:56:27.757 1352-1828/? I/TrafficMonitor: start expired. level:-1
2020-10-22 09:56:27.757 1352-1828/? I/TrafficMonitor: gettimer:interval=2000
2020-10-22 09:56:27.762 2249-2563/? I/TelephonyProxy: onOemHookRawEvent rawData:[B@8adbfa6
2020-10-22 09:56:27.764 2249-2249/? I/BoosterTelephonyCollector: unsol oem Data, moduleID=100, moduleLen=12, msgID=1, msgLen=8
2020-10-22 09:56:27.765 2249-2975/? D/nStackXDFinder: IfAddrMsgHandle:[85] :Interface rmnet0 got new address.
2020-10-22 09:56:27.765 2249-2975/? D/nStackXDFinder: IfAddrMsgHandle:[87] :Interface rmnet0 delete address.
2020-10-22 09:56:27.765 2249-2563/? I/TelephonyProxy: sendToMsgCenter moduleName:Telephony::eventName:EVENT_TELEPHONY_OEM_HOOK_RAW_EVENT
2020-10-22 09:56:27.766 2249-2563/? D/TelephonyProxy: publish OemHookRawEvent event
2020-10-22 09:56:27.766 2249-2563/? I/TelephonyProxy: onOemHookRawEvent rawData:[B@2c35de7

**Comment by janiokq** [comment]
g app:com.zhucheng.blue_app
2020-10-22 10:08:34.720 6012-6012/? V/Mms_TX_SysEvent: Intent received: action: android.net.conn.CONNECTIVITY_CHANGE
2020-10-22 10:08:34.720 6012-6175/? D/Mms_TX_SysEvent: handleConnectivityAction begin
2020-10-22 10:08:34.721 2308-2888/? D/PhoneInterfaceManager: [PhoneIntfMgr] isUserDataEnabled: subId=1 phoneId=1
2020-10-22 10:08:34.721 2308-2888/? D/PhoneInterfaceManager: [PhoneIntfMgr] isUserDataEnabled: subId=1 retVal=true
2020-10-22 10:08:34.722 6012-6175/? D/Mms_TX_SysEvent: handleConnectivityAction end
2020-10-22 10:08:34.780 8624-8624/? I/CloudAlbumSDK[10.6.0.302].NetBatteryManager: onReceive action: android.net.conn.CONNECTIVITY_CHANGE
2020-10-22 10:08:34.918 1352-1886/? E/WifiService: enforceCanAccessScanResults: hiding ssid and bssidUID 10159 has no location permission
2020-10-22 10:08:34.933 27960-27960/? I/HiTraceC: entered LogRegisterGetIdFun
2020-10-22 10:08:34.933 27960-27960/? I/HiTraceC: entered HiTraceInit
2020-10-22 10:08:34.966 10638-27964/? E/xingin.xhs:mul: No implementation found for void com.bun.lib.a.a(boolean) (tried Java_com_bun_lib_a_a and Java_com_bun_lib_a_a__Z)
2020-10-22 10:08:34.967 10638-27964/? E/MdidSdkHelper: InvocationTargetException
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.bun.miitmdid.core.MdidSdkHelper.InitSdk(Unknown Source:76)
        at cn.jiguang.u.a.a(Unknown Source:10)
        at cn.jiguang.u.a.call(Unknown Source:0)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
     Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void com.bun.lib.a.a(boolean) (tried Java_com_bun_lib_a_a and Java_com_bun_lib_a_a__Z)
        at com.bun.lib.a.a(Native Method)
        at com.bun.miitmdid.core.MdidSdk.<init>(Unknown Source:3)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at com.bun.miitmdid.core.MdidSdkHelper.InitSdk(Unknown Source:76) 
        at cn.jiguang.u.a.a(Unknown Source:10) 
        at cn.jiguang.u.a.call(Unknown Source:0) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:929) 
2020-10-22 10:08:34.967 10638-27964/? D/MdidSdkHelper: exception exit
2020-10-22 10:08:34.970 1352-1839/? I/ConnectivityService: releasing NetworkRequest [ REQUEST id=121, [ Transports: CELLULAR Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN Uid: 10203 DNN:  SSCMODE: 0 SNSSAI:  PduSessionType: 0 RouteBitmap: 0] ] (release request)
2020-10-22 10:08:34.970 27589-27589/? D/| JVER | Android | -: code=6001, message=fetch loginToken failed:[CT,（80800)WIFI切换超时]
2020-10-22 10:08:34.971 27589-27627/? I/flutter: handleMethod method = onReceiveLoginAuthCallBackEvent
2020-10-22 10:08:34.971 27589-27627/? I/flutter: 通过添加监听，获取到 loginAuthSyncApi 接口返回数据，code=6001,message = fetch loginToken failed:[CT,（80800)WIFI切换超时],operator = null

**Comment by jishaofeng89** [comment]
我了解的情况是WIFI环境下不支持。
